# Macro file for the initialization of example B2 
# in interactive session
#
# Set some default verbose
#/control/verbose 2 I COMMENTED THIS
/control/verbose 0
#/control/saveHistory  I COMMENTED THIS
#/run/verbose 2 I COMMENTED THIS
/run/verbose 0
#/tracking/verbose 3 I COMMENTED THIS
/tracking/verbose 0
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
#/control/execute vis.mac
