# Macro file for the visualization setting for the initialization phase 
# of the "test electron" when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
#/vis/open OGL 600x600-0+0
#/vis/open OGLIX
#
# NOTE: ALL OF THIS IS USELESS TO ME
# I DON'T EVEN HAVE THE APPROPRIATE VISUALIZATION PLUGINS
# FROM HERE...
# Use this open statement to create an OpenInventor view:
#/vis/open OIX
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# ...TO HERE

# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90. 180.
#
# Specify zoom value:
/vis/viewer/zoom 1.4
#
# Specify style (surface, wireframe, auxiliary edges,...)
#/vis/viewer/set/style wireframe
#/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 10 mm
/vis/scene/add/axes 0 0 1120 10 mm
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByAttribute
#/vis/modeling/trajectories/drawByAttribute-0/setAttribute IMag
#/vis/modeling/trajectories/drawByAttribute-0/addInterval enelow 0 keV 4.65 keV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval ene023 4.7 keV 5.0 keV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval ene034 5.7 keV 6.0 keV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval ene045 6.6 keV 6.9 keV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval ene054 7.3 keV 7.5 keV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval ene065 8.0 keV 8.3 keV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval ene100 10.0 keV 10.2 keV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval ene111 10.5 keV 10.7 keV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval ene122 11.0 keV 11.3 keV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval enehi  11.4 keV 100 keV
#Colors taken from "https://sashat.me/2017/01/11/list-of-20-simple-distinct-colors/"
#/vis/modeling/trajectories/drawByAttribute-0/enelow/setLineColourRGBA 0.5019 0.5019 0.5019 1
#/vis/modeling/trajectories/drawByAttribute-0/ene023/setLineColourRGBA 0.9019 0.0980 0.2941 1
#/vis/modeling/trajectories/drawByAttribute-0/ene034/setLineColourRGBA 0.2352 0.7058 0.2941 1
#/vis/modeling/trajectories/drawByAttribute-0/ene045/setLineColourRGBA 1.0000 1.0000 0.0980 1
#/vis/modeling/trajectories/drawByAttribute-0/ene054/setLineColourRGBA 0.0000 0.5098 0.7843 1
#/vis/modeling/trajectories/drawByAttribute-0/ene065/setLineColourRGBA 0.9607 0.5098 0.1882 1
#/vis/modeling/trajectories/drawByAttribute-0/ene100/setLineColourRGBA 0.5686 0.1176 0.7058 1
#/vis/modeling/trajectories/drawByAttribute-0/ene111/setLineColourRGBA 0.9803 0.7450 0.7450 1
#/vis/modeling/trajectories/drawByAttribute-0/ene122/setLineColourRGBA 0.6666 1.0000 0.7647 1
#/vis/modeling/trajectories/drawByAttribute-0/enehi/setLineColourRGBA  1.0000 1.0000 1.0000 1
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow I COMMENTED THIS
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set nu_e blue
/vis/modeling/trajectories/drawByParticleID-0/set Xe131 yellow
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
/vis/viewer/set/targetPoint 0 0 1120 mm
#/vis/viewer/flush
